### PR TITLE
fix(tuples): make doc work in tuple struct path

### PR DESCRIPTION
**Pull request by tiagolobocastro**
Add missing schema to unnamed structs with >1 element.
Fix issue with unnamed structs of 1 element caused by:
6429ef4
Fix usage of structs with Path with tuples: Path<(A,B,C)>

Unnamed struct element now get named starting from 0,1..... so that we
can keep the list of properties, though they should not really be used
anywhere else than a Path.

### CODE REVIEW

**Review by dunnock — COMMENTED** [review]
That looks good, can you please extend test to see if it's handling struct with 2 unnamed arguments? It's handled a bit differently and produces `object` now, would be great if that inherits description too

**Comment by tiagolobocastro** [comment]
> That looks good, can you please extend test to see if it's handling struct with 2 unnamed arguments? It's handled a bit differently and produces `object` now, would be great if that inherits description too

Yeah it produces object probably because unnamed structs with >1 elem are left with an empty schema.
I don't know if it's possible to improve things but I'll give it a go.

**Comment by tiagolobocastro** [comment]
Ok so we can get unnamed structs working by naming them such as they sort of are in rust, with names starting with 0, much like you'd do self.0?
That works pretty well for a Uri Path!
```
struct Test(String, String);
fn test(web::Path(test): web::Path<Test>) ...
```
Less so for a Body because you'd see the openapi scheme as:
```
{
  "0": "string",
  "1": "string"
}
```
But, that's a user choice I suppose... 
I'll push this up once I have time to tidy it up and write up the tests for this.

**Comment by tiagolobocastro** [comment]
@dunnock I've pushed, please let me know what you think.

**Review by dunnock — APPROVED** [review]
That's awesome! Sorry it took a while to dig into that

**Comment by tiagolobocastro** [comment]
> That's awesome! Sorry it took a while to dig into that

no worries, thank you!

**Comment by wafflespeanut** [comment]
Thank you for working on this!

**Pull request merged**
