### PR TITLE
cli: Drop reqwest support

### PR DESCRIPTION
**Pull request by MikailBag**
It decreases number of packages compiled from ~190 to ~130.
Please note that this PR conflicts with #191

### CODE REVIEW

**Comment by wafflespeanut** [comment]
I suppose we can get rid of that feature entirely and drop the support for loading spec from URLs. It’s too big a cost for a simple feature.

**Comment by MikailBag** [comment]
Should I drop reqwest support in this PR?

**Comment by wafflespeanut** [comment]
Feel free to!

**Comment by MikailBag** [comment]
CI is happy.

**Comment by wafflespeanut** [comment]
Awesome! Can you also please update `book/cli.md` to reflect on https://paperclip.waffles.space/cli.html#runtime-checks?

**Comment by MikailBag** [comment]
Done.

**Comment by wafflespeanut** [comment]
Great! Thank you for working on this! :smile:

**Pull request merged**
